export const ROUTES = {
    LOGIN: "/",
    MAP: "/map",
    PLACE_LIST: "/place/list",
    PLACE_EDIT: "/place/edit",
    PLACE_HISTORY_EDIT: "/place/history/edit",
    MY: "/my"
}

export const TEXT = {
    SEARCH: "검색",
    ADD: "ADD",
    PLACE_NAME: "장소 이름",
    CATEGORY: "카테고리",
    CATEGORY_MODIFY: "카테고리 수정",
    CATEGORY_MANAGEMENT: "카테고리 관리",
    ADDRESS: "주소",
    LATITUDE_LONGITUDE: "위도, 경도",
    LOCATION: "위치",
    MEMO: "메모",
    PICTURE: "사진",
    VIDEO: "영상",
    TAG: "태그",
    RATING: "별점",
    VISIT_AT: "방문일",
    RECENT_VISIT_AT: "최근 방문",
    PLACE_HISTORY: "방문 기록",
    CREATED: "작성일",
    MODIFY: "수정",
    DETAILS: "상세 보기",
    OK: "확인",
    CREATE: "생성",
    CANCEL: "취소",
    SHARE: "공유",
    DELETE: "삭제",
    PLACE_DELETE: "장소 삭제",
    PLACE_HISTORY_DELETE: "방문내역 삭제",
    YES: "예",
    NO: "아니오",
    TAKE_PHOTO: "사진 촬영하기",
    GET_POHOTO: "사진 가져오기",
    LOGIN: "로그인",
    LOGOUT: "로그아웃",
    WITHDRAW: "탈퇴",
    SORT: "정렬",
    CURRENT_LOCATION: "현재위치",
    USE_CURRENT_LOCATION: "현재위치 사용",
    CATEGORY_ADD: "카테고리 추가",
    CATEGORY_LIMIT: "카테고리 최대 수",
    CATEGORY_LIST: "카테고리 목록",
    ID: "ID",
    NAME: "이름",
    GENDER: "성별",
    AGREED_TERMS: "약관 동의",
    PHONE: "전화번호",
    BIRTHDAY: "생년월일",
    MALE: "남",
    FEMALE: "여",
    ACCOUNT_TYPE: "계정 유형",
    UPGRADE: "업그레이드",
    SUBSCRIPTION: "구독",
    UNSUBSCRIPTION: "구독 해지",
    SUBSCRIPTION_BENEFITS: "구독 혜택",
    SUBSCRIPTION_LIMITATIONS: "제약 사항",
    CATEGORY_ALL: "카테고리 전체",
    HISTORY_ADD: "방문 내역 추가",
    PRODUCT_CATEGORY_LIMIT:"최대 카테고리 저장 개수",
    PRODUCT_PLACE_LIMIT:"최대 장소 저장 개수",
    PRODUCT_PLACE_HISTORY_PHOTO_LIMIT:"최대 장소 사진 저장 개수",
    MSG_LOGIN_SUCCESS: "로그인 성공",
    MSG_LOGIN_FAILED: "로그인 실패",
    MSG_LOGOUT_CONFIRM: "로그아웃하시겠습니까?",
    MSG_WITHDRAW_CONFIRM: "서비스 탈퇴하시겠습니까?",
    MSG_DELETE_CONFORM: "삭제하시겠습니까?(복구불가)",
    MSG_PLACE_NAME: "장소 이름을 입력하세요.(10자 이내)",
    MSG_CATEGORY: "카테고리를 선택하세요.",
    MSG_CREATE_PLACE_CONFIRM: "장소를 등록하시겠습니까?",
    MSG_MODIFY_PLACE_CONFIRM: "장소를 수정하시겠습니까?",
    MSG_CREATE_PLACE_HISTORY_CONFIRM: "방문 내역을 등록하시겠습니까?",
    MSG_MODIFY_PLACE_HISTORY_CONFIRM: "방문 내역을 수정하시겠습니까?",
    MSG_DELETE_PLACE_CONFIRM: "장소를 삭제하시겠습니까?",
    MSG_DELETE_PLACE_HISTORY_CONFIRM: "방문 내역을 삭제하시겠습니까?",
    MSG_LOCATION_GUIDE: "지도에서 위치를 선택하세요.",
    MSG_TAG_GUIDE: "#태그를 입력하세요.",
    MSG_MEMO: "메모를 입력하세요.(50자 이내)",
    MSG_PICTURES_BASIC: "사진은 최대 10장 업로드 가능합니다.",
    MSG_PICTURES_PRO: "사진은 최대 30장 업로드 가능합니다.",
    MSG_SORTING_MENU: "정렬 기준을 선택하세요.",
    MSG_CATEGORY_FILTERING_MENU: "카테고리를 선택하세요.",
    MSG_SEARCH_HINT: "장소, #태그를 입력하세요.",
    MSG_SUBSCRIBE: "구독하시겠습니까?",
    MSG_SUBSCRIBE_COMPLETED: "구독이 완료되었습니다. 감사합니다.",
    MSG_UNSUBSCRIBE: "구독 해지하시겠습니까?",
    MSG_UNSUBSCRIBE_COMPLETED: "구독 해지가 완료되었습니다. 감사합니다.",
    MSG_IMAGE_DELETE: "선택한 이미지를 삭제하시겠습니까?",
    MSG_COMPLETED: "완료되었습니다.",
    MENU_CHOICE_ITEMS: "항목을 선택하세요",
    MENU_CATEGORY_CHOICE: "카테고리 선택",
    MENU_SORT_NAME_DESC: "장소 이름 내림차순",
    MENU_SORT_NAME_ASC: "장소 이름 오름차순",
    MENU_SORT_RECENT_RATING_DESC: "최근 별점 높은순",
    MENU_SORT_RECENT_RATING_ASC: "최근 별점 낮은순",
    MENU_SORT_RECENT_VISIT_DESC: "방문일 최근순",
    MENU_SORT_RECENT_VISIT_ASC: "방문일 오래된순",
    MENU_SORT_RECENT_VISIT_COUNT_DESC: "방문횟수 높은순",
    MENU_SORT_RECENT_VISIT_COUNT_ASC: "방문횟수 낮은순"

}

export const LOGOUT_REFERRER = {
    UNLINK: "UNLINK", // 로그아웃
    WITHDRAWAL_TERMS: "WITHDRAWAL_TERMS", // 약관 철회
    WITHDRAWAL_TOSS: "WITHDRAWAL_TOSS" // 탈퇴
}

export const ACCOUNT_TYPE_USER_BASIC = "BASIC"
export const ACCOUNT_TYPE_USER_PRO = "PRO"