export const CATEGORY_LIMIT_COUNT_BASE = 5
const CATEGORY_MENU_BASE_FOOD = "맛집"
const CATEGORY_MENU_BASE_CAFE = "카페"
const CATEGORY_MENU_BASE_HOTEL = "숙소"
const CATEGORY_MENU_BASE_TOUR = "관광"
const CATEGORY_MENU_BASE_ETC = "기타"
export const CATEGORY_MENU_BASE_ARR = [
    CATEGORY_MENU_BASE_FOOD,
    CATEGORY_MENU_BASE_CAFE,
    CATEGORY_MENU_BASE_HOTEL,
    CATEGORY_MENU_BASE_TOUR,
    CATEGORY_MENU_BASE_ETC

]